#scrape shield (nginx vip) based on well known static ip
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: shield_exporter
    scrape_interval: 2m
    scrape_timeout: 2m
    static_configs:
      - targets:
          - 192.168.99.26:9090 #static ip for master-depls/shieldv8
    relabel_configs:
      - source_labels:
          - job
        regex: "(.*)"
        target_label: bosh_deployment
        replacement: shared shieldv8


#alerts
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: shield
    rules:
      - alert: ShieldJobPaused
        expr: shield_job_paused == 1
        labels:
          service: shield
          severity: critical
        annotations:
          description: The Shield Job `{{$labels.job_name}}` at `{{$labels.environment}}/{{$labels.backend_name}}` has been in a `paused` state
          summary: Shield Job `{{$labels.job_name}}` at `{{$labels.environment}}/{{$labels.backend_name}}` paused
      - alert: ShieldJobFailed
        expr: shield_job_status == 4 and shield_job_paused == 0
        labels:
          service: shield
          severity: critical
        annotations:
          description: The Shield Job `{{$labels.job_name}}` at `{{$labels.environment}}/{{$labels.backend_name}}` has been in a `failing` state
          summary: Shield Job `{{$labels.job_name}}` at `{{$labels.environment}}/{{$labels.backend_name}}` failed

